let BoxplotData = [
  {
    index: 0,
    cluster: 1,
    KAB_KOTA: "KONAWE KEPULAUAN",
    ipm: 65.73,
  },
  {
    index: 1,
    cluster: 3,
    KAB_KOTA: "MOROWALI UTARA",
    ipm: 68.48,
  },
  {
    index: 2,
    cluster: 1,
    KAB_KOTA: "MUSI RAWAS UTARA",
    ipm: 64.93,
  },
  {
    index: 3,
    cluster: 3,
    KAB_KOTA: "ACEH BARAT",
    ipm: 71.67,
  },
  {
    index: 4,
    cluster: 0,
    KAB_KOTA: "ACEH BARAT DAYA",
    ipm: 66.99,
  },
  {
    index: 5,
    cluster: 3,
    KAB_KOTA: "ACEH BESAR",
    ipm: 73.58,
  },
  {
    index: 6,
    cluster: 3,
    KAB_KOTA: "ACEH JAYA",
    ipm: 69.84,
  },
  {
    index: 7,
    cluster: 3,
    KAB_KOTA: "ACEH SELATAN",
    ipm: 67.44,
  },
  {
    index: 8,
    cluster: 3,
    KAB_KOTA: "ACEH SINGKIL",
    ipm: 69.22,
  },
  {
    index: 9,
    cluster: 3,
    KAB_KOTA: "ACEH TAMIANG",
    ipm: 69.48,
  },
  {
    index: 10,
    cluster: 3,
    KAB_KOTA: "ACEH TENGAH",
    ipm: 73.37,
  },
  {
    index: 11,
    cluster: 1,
    KAB_KOTA: "ACEH TENGGARA",
    ipm: 69.44,
  },
  {
    index: 12,
    cluster: 3,
    KAB_KOTA: "ACEH TIMUR",
    ipm: 67.83,
  },
  {
    index: 13,
    cluster: 3,
    KAB_KOTA: "ACEH UTARA",
    ipm: 69.46,
  },
  {
    index: 14,
    cluster: 3,
    KAB_KOTA: "AGAM",
    ipm: 72.57,
  },
  {
    index: 15,
    cluster: 3,
    KAB_KOTA: "ALOR",
    ipm: 61.37,
  },
  {
    index: 16,
    cluster: 3,
    KAB_KOTA: "ASAHAN",
    ipm: 70.49,
  },
  {
    index: 17,
    cluster: 1,
    KAB_KOTA: "ASMAT",
    ipm: 51.29,
  },
  {
    index: 18,
    cluster: 2,
    KAB_KOTA: "BADUNG",
    ipm: 81.83,
  },
  {
    index: 19,
    cluster: 1,
    KAB_KOTA: "BALANGAN",
    ipm: 69.11,
  },
  {
    index: 20,
    cluster: 0,
    KAB_KOTA: "BANDUNG",
    ipm: 72.73,
  },
  {
    index: 21,
    cluster: 0,
    KAB_KOTA: "BANDUNG BARAT",
    ipm: 68.29,
  },
  {
    index: 22,
    cluster: 3,
    KAB_KOTA: "BANGGAI",
    ipm: 70.6,
  },
  {
    index: 23,
    cluster: 3,
    KAB_KOTA: "BANGGAI KEPULAUAN",
    ipm: 65.61,
  },
  {
    index: 24,
    cluster: 3,
    KAB_KOTA: "BANGGAI LAUT",
    ipm: 65.65,
  },
  {
    index: 25,
    cluster: 0,
    KAB_KOTA: "BANGKA",
    ipm: 72.46,
  },
  {
    index: 26,
    cluster: 0,
    KAB_KOTA: "BANGKA BARAT",
    ipm: 69.6,
  },
  {
    index: 27,
    cluster: 3,
    KAB_KOTA: "BANGKA SELATAN",
    ipm: 67.06,
  },
  {
    index: 28,
    cluster: 3,
    KAB_KOTA: "BANGKA TENGAH",
    ipm: 70.89,
  },
  {
    index: 29,
    cluster: 3,
    KAB_KOTA: "BANGKALAN",
    ipm: 64.36,
  },
  {
    index: 30,
    cluster: 0,
    KAB_KOTA: "BANGLI",
    ipm: 69.37,
  },
  {
    index: 31,
    cluster: 0,
    KAB_KOTA: "BANJAR",
    ipm: 69.89,
  },
  {
    index: 32,
    cluster: 3,
    KAB_KOTA: "BANJARNEGARA",
    ipm: 67.86,
  },
  {
    index: 33,
    cluster: 0,
    KAB_KOTA: "BANTAENG",
    ipm: 68.99,
  },
  {
    index: 34,
    cluster: 0,
    KAB_KOTA: "BANTUL",
    ipm: 80.28,
  },
  {
    index: 35,
    cluster: 0,
    KAB_KOTA: "BANYUMAS",
    ipm: 72.44,
  },
  {
    index: 36,
    cluster: 1,
    KAB_KOTA: "BANYUWANGI",
    ipm: 71.38,
  },
  {
    index: 37,
    cluster: 3,
    KAB_KOTA: "BARITO KUALA",
    ipm: 66.64,
  },
  {
    index: 38,
    cluster: 3,
    KAB_KOTA: "BARITO SELATAN",
    ipm: 70.54,
  },
  {
    index: 39,
    cluster: 3,
    KAB_KOTA: "BARITO TIMUR",
    ipm: 71.47,
  },
  {
    index: 40,
    cluster: 3,
    KAB_KOTA: "BARITO UTARA",
    ipm: 70.79,
  },
  {
    index: 41,
    cluster: 3,
    KAB_KOTA: "BARRU",
    ipm: 71.13,
  },
  {
    index: 42,
    cluster: 0,
    KAB_KOTA: "BATANG",
    ipm: 68.92,
  },
  {
    index: 43,
    cluster: 0,
    KAB_KOTA: "BATU BARA",
    ipm: 68.58,
  },
  {
    index: 44,
    cluster: 2,
    KAB_KOTA: "BEKASI",
    ipm: 74.45,
  },
  {
    index: 45,
    cluster: 0,
    KAB_KOTA: "BELITUNG",
    ipm: 72.57,
  },
  {
    index: 46,
    cluster: 0,
    KAB_KOTA: "BELITUNG TIMUR",
    ipm: 71.42,
  },
  {
    index: 47,
    cluster: 3,
    KAB_KOTA: "BELU",
    ipm: 62.77,
  },
  {
    index: 48,
    cluster: 3,
    KAB_KOTA: "BENER MERIAH",
    ipm: 73.27,
  },
  {
    index: 49,
    cluster: 1,
    KAB_KOTA: "BENGKALIS",
    ipm: 73.58,
  },
  {
    index: 50,
    cluster: 1,
    KAB_KOTA: "BENGKAYANG",
    ipm: 68.04,
  },
  {
    index: 51,
    cluster: 3,
    KAB_KOTA: "BENGKULU SELATAN",
    ipm: 70.75,
  },
  {
    index: 52,
    cluster: 3,
    KAB_KOTA: "BENGKULU TENGAH",
    ipm: 67.96,
  },
  {
    index: 53,
    cluster: 3,
    KAB_KOTA: "BENGKULU UTARA",
    ipm: 69.28,
  },
  {
    index: 54,
    cluster: 1,
    KAB_KOTA: "BERAU",
    ipm: 75.2,
  },
  {
    index: 55,
    cluster: 1,
    KAB_KOTA: "BIAK NUMFOR",
    ipm: 72.33,
  },
  {
    index: 56,
    cluster: 3,
    KAB_KOTA: "BIMA",
    ipm: 66.66,
  },
  {
    index: 57,
    cluster: 0,
    KAB_KOTA: "BINTAN",
    ipm: 74.57,
  },
  {
    index: 58,
    cluster: 3,
    KAB_KOTA: "BIREUEN",
    ipm: 72.33,
  },
  {
    index: 59,
    cluster: 3,
    KAB_KOTA: "BLITAR",
    ipm: 71.05,
  },
  {
    index: 60,
    cluster: 3,
    KAB_KOTA: "BLORA",
    ipm: 69.37,
  },
  {
    index: 61,
    cluster: 3,
    KAB_KOTA: "BOALEMO",
    ipm: 66.42,
  },
  {
    index: 62,
    cluster: 2,
    KAB_KOTA: "BOGOR",
    ipm: 70.6,
  },
  {
    index: 63,
    cluster: 0,
    KAB_KOTA: "BOJONEGORO",
    ipm: 69.59,
  },
  {
    index: 64,
    cluster: 3,
    KAB_KOTA: "BOLAANG MONGONDOW",
    ipm: 68.16,
  },
  {
    index: 65,
    cluster: 3,
    KAB_KOTA: "BOLAANG MONGONDOW SELATAN",
    ipm: 65.42,
  },
  {
    index: 66,
    cluster: 3,
    KAB_KOTA: "BOLAANG MONGONDOW TIMUR",
    ipm: 66.55,
  },
  {
    index: 67,
    cluster: 1,
    KAB_KOTA: "BOLAANG MONGONDOW UTARA",
    ipm: 67.39,
  },
  {
    index: 68,
    cluster: 1,
    KAB_KOTA: "BOMBANA",
    ipm: 66.25,
  },
  {
    index: 69,
    cluster: 3,
    KAB_KOTA: "BONDOWOSO",
    ipm: 66.59,
  },
  {
    index: 70,
    cluster: 0,
    KAB_KOTA: "BONE",
    ipm: 66.4,
  },
  {
    index: 71,
    cluster: 3,
    KAB_KOTA: "BONE BOLANGO",
    ipm: 70.25,
  },
  {
    index: 72,
    cluster: 3,
    KAB_KOTA: "BOYOLALI",
    ipm: 74.4,
  },
  {
    index: 73,
    cluster: 3,
    KAB_KOTA: "BREBES",
    ipm: 66.32,
  },
  {
    index: 74,
    cluster: 0,
    KAB_KOTA: "BULELENG",
    ipm: 72.56,
  },
  {
    index: 75,
    cluster: 3,
    KAB_KOTA: "BULUKUMBA",
    ipm: 69.62,
  },
  {
    index: 76,
    cluster: 3,
    KAB_KOTA: "BULUNGAN",
    ipm: 71.8,
  },
  {
    index: 77,
    cluster: 3,
    KAB_KOTA: "BUNGO",
    ipm: 70.15,
  },
  {
    index: 78,
    cluster: 3,
    KAB_KOTA: "BUOL",
    ipm: 68.25,
  },
  {
    index: 79,
    cluster: 3,
    KAB_KOTA: "BURU",
    ipm: 69.33,
  },
  {
    index: 80,
    cluster: 1,
    KAB_KOTA: "BURU SELATAN",
    ipm: 64.8,
  },
  {
    index: 81,
    cluster: 3,
    KAB_KOTA: "BUTON",
    ipm: 66.32,
  },
  {
    index: 82,
    cluster: 1,
    KAB_KOTA: "BUTON SELATAN",
    ipm: 64.99,
  },
  {
    index: 83,
    cluster: 1,
    KAB_KOTA: "BUTON TENGAH",
    ipm: 64.55,
  },
  {
    index: 84,
    cluster: 1,
    KAB_KOTA: "BUTON UTARA",
    ipm: 68.08,
  },
  {
    index: 85,
    cluster: 3,
    KAB_KOTA: "CIAMIS",
    ipm: 70.93,
  },
  {
    index: 86,
    cluster: 0,
    KAB_KOTA: "CIANJUR",
    ipm: 65.56,
  },
  {
    index: 87,
    cluster: 0,
    KAB_KOTA: "CILACAP",
    ipm: 70.42,
  },
  {
    index: 88,
    cluster: 0,
    KAB_KOTA: "CIREBON",
    ipm: 69.12,
  },
  {
    index: 89,
    cluster: 3,
    KAB_KOTA: "DAIRI",
    ipm: 71.84,
  },
  {
    index: 90,
    cluster: 1,
    KAB_KOTA: "DEIYAI",
    ipm: 49.96,
  },
  {
    index: 91,
    cluster: 2,
    KAB_KOTA: "DELI SERDANG",
    ipm: 75.53,
  },
  {
    index: 92,
    cluster: 0,
    KAB_KOTA: "DEMAK",
    ipm: 72.57,
  },
  {
    index: 93,
    cluster: 3,
    KAB_KOTA: "DHARMASRAYA",
    ipm: 71.76,
  },
  {
    index: 94,
    cluster: 1,
    KAB_KOTA: "DOGIYAI",
    ipm: 55,
  },
  {
    index: 95,
    cluster: 3,
    KAB_KOTA: "DOMPU",
    ipm: 68.45,
  },
  {
    index: 96,
    cluster: 3,
    KAB_KOTA: "DONGGALA",
    ipm: 65.72,
  },
  {
    index: 97,
    cluster: 1,
    KAB_KOTA: "EMPAT LAWANG",
    ipm: 65.39,
  },
  {
    index: 98,
    cluster: 1,
    KAB_KOTA: "ENDE",
    ipm: 67.3,
  },
  {
    index: 99,
    cluster: 3,
    KAB_KOTA: "ENREKANG",
    ipm: 72.91,
  },
  {
    index: 100,
    cluster: 3,
    KAB_KOTA: "FAKFAK",
    ipm: 68.52,
  },
  {
    index: 101,
    cluster: 3,
    KAB_KOTA: "FLORES TIMUR",
    ipm: 64.22,
  },
  {
    index: 102,
    cluster: 3,
    KAB_KOTA: "GARUT",
    ipm: 66.45,
  },
  {
    index: 103,
    cluster: 3,
    KAB_KOTA: "GAYO LUES",
    ipm: 67.56,
  },
  {
    index: 104,
    cluster: 2,
    KAB_KOTA: "GIANYAR",
    ipm: 77.7,
  },
  {
    index: 105,
    cluster: 3,
    KAB_KOTA: "GORONTALO",
    ipm: 67.34,
  },
  {
    index: 106,
    cluster: 1,
    KAB_KOTA: "GORONTALO UTARA",
    ipm: 65.21,
  },
  {
    index: 107,
    cluster: 0,
    KAB_KOTA: "GOWA",
    ipm: 70.29,
  },
  {
    index: 108,
    cluster: 2,
    KAB_KOTA: "GRESIK",
    ipm: 76.5,
  },
  {
    index: 109,
    cluster: 3,
    KAB_KOTA: "GROBOGAN",
    ipm: 70.41,
  },
  {
    index: 110,
    cluster: 3,
    KAB_KOTA: "GUNUNG MAS",
    ipm: 71.03,
  },
  {
    index: 111,
    cluster: 1,
    KAB_KOTA: "HALMAHERA BARAT",
    ipm: 65.56,
  },
  {
    index: 112,
    cluster: 1,
    KAB_KOTA: "HALMAHERA SELATAN",
    ipm: 64.19,
  },
  {
    index: 113,
    cluster: 2,
    KAB_KOTA: "HALMAHERA TENGAH",
    ipm: 65.82,
  },
  {
    index: 114,
    cluster: 1,
    KAB_KOTA: "HALMAHERA TIMUR",
    ipm: 67,
  },
  {
    index: 115,
    cluster: 1,
    KAB_KOTA: "HALMAHERA UTARA",
    ipm: 67.82,
  },
  {
    index: 116,
    cluster: 0,
    KAB_KOTA: "HULU SUNGAI SELATAN",
    ipm: 69.21,
  },
  {
    index: 117,
    cluster: 0,
    KAB_KOTA: "HULU SUNGAI TENGAH",
    ipm: 69.05,
  },
  {
    index: 118,
    cluster: 0,
    KAB_KOTA: "HULU SUNGAI UTARA",
    ipm: 66.12,
  },
  {
    index: 119,
    cluster: 3,
    KAB_KOTA: "HUMBANG HASUNDUTAN",
    ipm: 69.41,
  },
  {
    index: 120,
    cluster: 3,
    KAB_KOTA: "INDRAGIRI HILIR",
    ipm: 66.63,
  },
  {
    index: 121,
    cluster: 0,
    KAB_KOTA: "INDRAGIRI HULU",
    ipm: 70.01,
  },
  {
    index: 122,
    cluster: 3,
    KAB_KOTA: "INDRAMAYU",
    ipm: 67.64,
  },
  {
    index: 123,
    cluster: 1,
    KAB_KOTA: "INTAN JAYA",
    ipm: 48.34,
  },
  {
    index: 124,
    cluster: 1,
    KAB_KOTA: "JAYAPURA",
    ipm: 72.03,
  },
  {
    index: 125,
    cluster: 1,
    KAB_KOTA: "JAYAWIJAYA",
    ipm: 58.67,
  },
  {
    index: 126,
    cluster: 0,
    KAB_KOTA: "JEMBER",
    ipm: 67.32,
  },
  {
    index: 127,
    cluster: 0,
    KAB_KOTA: "JEMBRANA",
    ipm: 72.75,
  },
  {
    index: 128,
    cluster: 3,
    KAB_KOTA: "JENEPONTO",
    ipm: 64.56,
  },
  {
    index: 129,
    cluster: 0,
    KAB_KOTA: "JEPARA",
    ipm: 72.36,
  },
  {
    index: 130,
    cluster: 0,
    KAB_KOTA: "JOMBANG",
    ipm: 73.45,
  },
  {
    index: 131,
    cluster: 1,
    KAB_KOTA: "KAIMANA",
    ipm: 65.31,
  },
  {
    index: 132,
    cluster: 3,
    KAB_KOTA: "KAMPAR",
    ipm: 73.02,
  },
  {
    index: 133,
    cluster: 1,
    KAB_KOTA: "KAPUAS",
    ipm: 69.63,
  },
  {
    index: 134,
    cluster: 1,
    KAB_KOTA: "KAPUAS HULU",
    ipm: 65.75,
  },
  {
    index: 135,
    cluster: 3,
    KAB_KOTA: "KARANGANYAR",
    ipm: 75.99,
  },
  {
    index: 136,
    cluster: 0,
    KAB_KOTA: "KARANGASEM",
    ipm: 67.36,
  },
  {
    index: 137,
    cluster: 2,
    KAB_KOTA: "KARAWANG",
    ipm: 70.94,
  },
  {
    index: 138,
    cluster: 2,
    KAB_KOTA: "KARIMUN",
    ipm: 71.7,
  },
  {
    index: 139,
    cluster: 3,
    KAB_KOTA: "KARO",
    ipm: 74.83,
  },
  {
    index: 140,
    cluster: 1,
    KAB_KOTA: "KATINGAN",
    ipm: 68.89,
  },
  {
    index: 141,
    cluster: 3,
    KAB_KOTA: "KAUR",
    ipm: 67.17,
  },
  {
    index: 142,
    cluster: 3,
    KAB_KOTA: "KAYONG UTARA",
    ipm: 62.9,
  },
  {
    index: 143,
    cluster: 3,
    KAB_KOTA: "KEBUMEN",
    ipm: 70.05,
  },
  {
    index: 144,
    cluster: 0,
    KAB_KOTA: "KEDIRI",
    ipm: 72.56,
  },
  {
    index: 145,
    cluster: 1,
    KAB_KOTA: "KEEROM",
    ipm: 66.49,
  },
  {
    index: 146,
    cluster: 0,
    KAB_KOTA: "KENDAL",
    ipm: 72.5,
  },
  {
    index: 147,
    cluster: 3,
    KAB_KOTA: "KEPAHIANG",
    ipm: 68.62,
  },
  {
    index: 148,
    cluster: 3,
    KAB_KOTA: "KEPULAUAN ANAMBAS",
    ipm: 69.23,
  },
  {
    index: 149,
    cluster: 1,
    KAB_KOTA: "KEPULAUAN ARU",
    ipm: 63.83,
  },
  {
    index: 150,
    cluster: 3,
    KAB_KOTA: "KEPULAUAN MENTAWAI",
    ipm: 61.35,
  },
  {
    index: 151,
    cluster: 0,
    KAB_KOTA: "KEPULAUAN MERANTI",
    ipm: 65.7,
  },
  {
    index: 152,
    cluster: 1,
    KAB_KOTA: "KEPULAUAN SELAYAR",
    ipm: 67.76,
  },
  {
    index: 153,
    cluster: 1,
    KAB_KOTA: "KEPULAUAN SULA",
    ipm: 63.8,
  },
  {
    index: 154,
    cluster: 1,
    KAB_KOTA: "KEPULAUAN TALAUD",
    ipm: 69.83,
  },
  {
    index: 155,
    cluster: 1,
    KAB_KOTA: "MALUKU TENGGARA BARAT",
    ipm: 62.97,
  },
  {
    index: 156,
    cluster: 1,
    KAB_KOTA: "KEPULAUAN YAPEN",
    ipm: 67.72,
  },
  {
    index: 157,
    cluster: 3,
    KAB_KOTA: "KERINCI",
    ipm: 71.45,
  },
  {
    index: 158,
    cluster: 3,
    KAB_KOTA: "KETAPANG",
    ipm: 67.43,
  },
  {
    index: 159,
    cluster: 3,
    KAB_KOTA: "KLATEN",
    ipm: 76.12,
  },
  {
    index: 160,
    cluster: 0,
    KAB_KOTA: "KLUNGKUNG",
    ipm: 71.75,
  },
  {
    index: 161,
    cluster: 3,
    KAB_KOTA: "KOLAKA",
    ipm: 73.56,
  },
  {
    index: 162,
    cluster: 1,
    KAB_KOTA: "KOLAKA TIMUR",
    ipm: 67.76,
  },
  {
    index: 163,
    cluster: 3,
    KAB_KOTA: "KOLAKA UTARA",
    ipm: 69.5,
  },
  {
    index: 164,
    cluster: 3,
    KAB_KOTA: "KONAWE",
    ipm: 71.48,
  },
  {
    index: 165,
    cluster: 1,
    KAB_KOTA: "KONAWE SELATAN",
    ipm: 68.58,
  },
  {
    index: 166,
    cluster: 1,
    KAB_KOTA: "KONAWE UTARA",
    ipm: 70.23,
  },
  {
    index: 167,
    cluster: 0,
    KAB_KOTA: "KOTAWARINGIN BARAT",
    ipm: 73.07,
  },
  {
    index: 168,
    cluster: 0,
    KAB_KOTA: "KOTAWARINGIN TIMUR",
    ipm: 71.38,
  },
  {
    index: 169,
    cluster: 3,
    KAB_KOTA: "KUANTAN SINGINGI",
    ipm: 70.6,
  },
  {
    index: 170,
    cluster: 0,
    KAB_KOTA: "KUBU RAYA",
    ipm: 68.16,
  },
  {
    index: 171,
    cluster: 0,
    KAB_KOTA: "KUDUS",
    ipm: 75.16,
  },
  {
    index: 172,
    cluster: 0,
    KAB_KOTA: "KULON PROGO",
    ipm: 74.71,
  },
  {
    index: 173,
    cluster: 3,
    KAB_KOTA: "KUNINGAN",
    ipm: 69.71,
  },
  {
    index: 174,
    cluster: 3,
    KAB_KOTA: "KUPANG",
    ipm: 64.41,
  },
  {
    index: 175,
    cluster: 1,
    KAB_KOTA: "KUTAI BARAT",
    ipm: 72.07,
  },
  {
    index: 176,
    cluster: 0,
    KAB_KOTA: "KUTAI KARTANEGARA",
    ipm: 74.06,
  },
  {
    index: 177,
    cluster: 3,
    KAB_KOTA: "KUTAI TIMUR",
    ipm: 73.81,
  },
  {
    index: 178,
    cluster: 3,
    KAB_KOTA: "LAHAT",
    ipm: 67.58,
  },
  {
    index: 179,
    cluster: 1,
    KAB_KOTA: "LAMANDAU",
    ipm: 70.58,
  },
  {
    index: 180,
    cluster: 1,
    KAB_KOTA: "LAMONGAN",
    ipm: 73.12,
  },
  {
    index: 181,
    cluster: 3,
    KAB_KOTA: "LAMPUNG BARAT",
    ipm: 67.9,
  },
  {
    index: 182,
    cluster: 3,
    KAB_KOTA: "LAMPUNG SELATAN",
    ipm: 68.49,
  },
  {
    index: 183,
    cluster: 3,
    KAB_KOTA: "LAMPUNG TENGAH",
    ipm: 70.23,
  },
  {
    index: 184,
    cluster: 3,
    KAB_KOTA: "LAMPUNG TIMUR",
    ipm: 69.66,
  },
  {
    index: 185,
    cluster: 3,
    KAB_KOTA: "LAMPUNG UTARA",
    ipm: 67.89,
  },
  {
    index: 186,
    cluster: 3,
    KAB_KOTA: "LANDAK",
    ipm: 66.21,
  },
  {
    index: 187,
    cluster: 3,
    KAB_KOTA: "LANGKAT",
    ipm: 71.35,
  },
  {
    index: 188,
    cluster: 1,
    KAB_KOTA: "LANNY JAYA",
    ipm: 48.68,
  },
  {
    index: 189,
    cluster: 3,
    KAB_KOTA: "LEBAK",
    ipm: 64.03,
  },
  {
    index: 190,
    cluster: 3,
    KAB_KOTA: "LEBONG",
    ipm: 67.46,
  },
  {
    index: 191,
    cluster: 1,
    KAB_KOTA: "LEMBATA",
    ipm: 64.75,
  },
  {
    index: 192,
    cluster: 3,
    KAB_KOTA: "LIMA PULUH KOTA",
    ipm: 69.68,
  },
  {
    index: 193,
    cluster: 3,
    KAB_KOTA: "LINGGA",
    ipm: 65.83,
  },
  {
    index: 194,
    cluster: 3,
    KAB_KOTA: "LOMBOK BARAT",
    ipm: 68.61,
  },
  {
    index: 195,
    cluster: 3,
    KAB_KOTA: "LOMBOK TENGAH",
    ipm: 66.72,
  },
  {
    index: 196,
    cluster: 1,
    KAB_KOTA: "LOMBOK TIMUR",
    ipm: 66.66,
  },
  {
    index: 197,
    cluster: 3,
    KAB_KOTA: "LOMBOK UTARA",
    ipm: 64.77,
  },
  {
    index: 198,
    cluster: 0,
    KAB_KOTA: "LUMAJANG",
    ipm: 66.07,
  },
  {
    index: 199,
    cluster: 3,
    KAB_KOTA: "LUWU",
    ipm: 70.85,
  },
  {
    index: 200,
    cluster: 0,
    KAB_KOTA: "LUWU TIMUR",
    ipm: 73.34,
  },
  {
    index: 201,
    cluster: 1,
    KAB_KOTA: "LUWU UTARA",
    ipm: 70.02,
  },
  {
    index: 202,
    cluster: 3,
    KAB_KOTA: "MADIUN",
    ipm: 71.88,
  },
  {
    index: 203,
    cluster: 3,
    KAB_KOTA: "MAGELANG",
    ipm: 70.12,
  },
  {
    index: 204,
    cluster: 3,
    KAB_KOTA: "MAGETAN",
    ipm: 74.15,
  },
  {
    index: 205,
    cluster: 1,
    KAB_KOTA: "MAHAKAM ULU",
    ipm: 67.95,
  },
  {
    index: 206,
    cluster: 0,
    KAB_KOTA: "MAJALENGKA",
    ipm: 67.81,
  },
  {
    index: 207,
    cluster: 3,
    KAB_KOTA: "MAJENE",
    ipm: 67.29,
  },
  {
    index: 208,
    cluster: 3,
    KAB_KOTA: "MALAKA",
    ipm: 60.42,
  },
  {
    index: 209,
    cluster: 0,
    KAB_KOTA: "MALANG",
    ipm: 70.6,
  },
  {
    index: 210,
    cluster: 3,
    KAB_KOTA: "MALINAU",
    ipm: 72.32,
  },
  {
    index: 211,
    cluster: 1,
    KAB_KOTA: "MALUKU BARAT DAYA",
    ipm: 62.37,
  },
  {
    index: 212,
    cluster: 3,
    KAB_KOTA: "MALUKU TENGAH",
    ipm: 71.32,
  },
  {
    index: 213,
    cluster: 1,
    KAB_KOTA: "MALUKU TENGGARA",
    ipm: 66.33,
  },
  {
    index: 214,
    cluster: 3,
    KAB_KOTA: "MAMASA",
    ipm: 66.63,
  },
  {
    index: 215,
    cluster: 1,
    KAB_KOTA: "MAMBERAMO RAYA",
    ipm: 52.18,
  },
  {
    index: 216,
    cluster: 1,
    KAB_KOTA: "MAMBERAMO TENGAH",
    ipm: 48.32,
  },
  {
    index: 217,
    cluster: 3,
    KAB_KOTA: "MAMUJU",
    ipm: 68.32,
  },
  {
    index: 218,
    cluster: 1,
    KAB_KOTA: "MAMUJU TENGAH",
    ipm: 66.18,
  },
  {
    index: 219,
    cluster: 1,
    KAB_KOTA: "MAMUJU UTARA",
    ipm: 68.03,
  },
  {
    index: 220,
    cluster: 3,
    KAB_KOTA: "MANDAILING NATAL",
    ipm: 67.19,
  },
  {
    index: 221,
    cluster: 1,
    KAB_KOTA: "MANGGARAI",
    ipm: 65.01,
  },
  {
    index: 222,
    cluster: 0,
    KAB_KOTA: "MANGGARAI BARAT",
    ipm: 64.17,
  },
  {
    index: 223,
    cluster: 1,
    KAB_KOTA: "MANGGARAI TIMUR",
    ipm: 61.37,
  },
  {
    index: 224,
    cluster: 1,
    KAB_KOTA: "MANOKWARI",
    ipm: 72.02,
  },
  {
    index: 225,
    cluster: 1,
    KAB_KOTA: "MANOKWARI SELATAN",
    ipm: 59.85,
  },
  {
    index: 226,
    cluster: 1,
    KAB_KOTA: "MAPPI",
    ipm: 58.7,
  },
  {
    index: 227,
    cluster: 0,
    KAB_KOTA: "MAROS",
    ipm: 70.41,
  },
  {
    index: 228,
    cluster: 1,
    KAB_KOTA: "MAYBRAT",
    ipm: 59.7,
  },
  {
    index: 229,
    cluster: 3,
    KAB_KOTA: "MELAWI",
    ipm: 65.87,
  },
  {
    index: 230,
    cluster: 3,
    KAB_KOTA: "MEMPAWAH",
    ipm: 66.03,
  },
  {
    index: 231,
    cluster: 3,
    KAB_KOTA: "MERANGIN",
    ipm: 69.53,
  },
  {
    index: 232,
    cluster: 1,
    KAB_KOTA: "MERAUKE",
    ipm: 70.49,
  },
  {
    index: 233,
    cluster: 1,
    KAB_KOTA: "MESUJI",
    ipm: 64.04,
  },
  {
    index: 234,
    cluster: 0,
    KAB_KOTA: "MIMIKA",
    ipm: 74.48,
  },
  {
    index: 235,
    cluster: 3,
    KAB_KOTA: "MINAHASA",
    ipm: 75.73,
  },
  {
    index: 236,
    cluster: 3,
    KAB_KOTA: "MINAHASA SELATAN",
    ipm: 72.32,
  },
  {
    index: 237,
    cluster: 3,
    KAB_KOTA: "MINAHASA TENGGARA",
    ipm: 71.06,
  },
  {
    index: 238,
    cluster: 3,
    KAB_KOTA: "MINAHASA UTARA",
    ipm: 74.11,
  },
  {
    index: 239,
    cluster: 0,
    KAB_KOTA: "MOJOKERTO",
    ipm: 74.15,
  },
  {
    index: 240,
    cluster: 0,
    KAB_KOTA: "MOROWALI",
    ipm: 72.29,
  },
  {
    index: 241,
    cluster: 3,
    KAB_KOTA: "MUARA ENIM",
    ipm: 68.86,
  },
  {
    index: 242,
    cluster: 3,
    KAB_KOTA: "MUARO JAMBI",
    ipm: 69.55,
  },
  {
    index: 243,
    cluster: 3,
    KAB_KOTA: "MUKOMUKO",
    ipm: 68.64,
  },
  {
    index: 244,
    cluster: 1,
    KAB_KOTA: "MUNA",
    ipm: 69.17,
  },
  {
    index: 245,
    cluster: 1,
    KAB_KOTA: "MUNA BARAT",
    ipm: 65.48,
  },
  {
    index: 246,
    cluster: 3,
    KAB_KOTA: "MURUNG RAYA",
    ipm: 68.12,
  },
  {
    index: 247,
    cluster: 1,
    KAB_KOTA: "MUSI BANYUASIN",
    ipm: 68.1,
  },
  {
    index: 248,
    cluster: 3,
    KAB_KOTA: "MUSI RAWAS",
    ipm: 67.01,
  },
  {
    index: 249,
    cluster: 3,
    KAB_KOTA: "NABIRE",
    ipm: 69.15,
  },
  {
    index: 250,
    cluster: 3,
    KAB_KOTA: "NAGAN RAYA",
    ipm: 69.31,
  },
  {
    index: 251,
    cluster: 3,
    KAB_KOTA: "NAGEKEO",
    ipm: 65.82,
  },
  {
    index: 252,
    cluster: 3,
    KAB_KOTA: "NATUNA",
    ipm: 73.09,
  },
  {
    index: 253,
    cluster: 1,
    KAB_KOTA: "NDUGA",
    ipm: 32.84,
  },
  {
    index: 254,
    cluster: 3,
    KAB_KOTA: "NGADA",
    ipm: 67.88,
  },
  {
    index: 255,
    cluster: 0,
    KAB_KOTA: "NGANJUK",
    ipm: 71.97,
  },
  {
    index: 256,
    cluster: 3,
    KAB_KOTA: "NGAWI",
    ipm: 71.04,
  },
  {
    index: 257,
    cluster: 1,
    KAB_KOTA: "NIAS",
    ipm: 62.74,
  },
  {
    index: 258,
    cluster: 1,
    KAB_KOTA: "NIAS BARAT",
    ipm: 61.99,
  },
  {
    index: 259,
    cluster: 1,
    KAB_KOTA: "NIAS SELATAN",
    ipm: 62.35,
  },
  {
    index: 260,
    cluster: 1,
    KAB_KOTA: "NIAS UTARA",
    ipm: 62.82,
  },
  {
    index: 261,
    cluster: 3,
    KAB_KOTA: "NUNUKAN",
    ipm: 66.46,
  },
  {
    index: 262,
    cluster: 1,
    KAB_KOTA: "OGAN KOMERING ULU SELATAN",
    ipm: 65.34,
  },
  {
    index: 263,
    cluster: 3,
    KAB_KOTA: "OGAN KOMERING ULU TIMUR",
    ipm: 69.58,
  },
  {
    index: 264,
    cluster: 3,
    KAB_KOTA: "OGAN ILIR",
    ipm: 67.17,
  },
  {
    index: 265,
    cluster: 0,
    KAB_KOTA: "OGAN KOMERING ILIR",
    ipm: 67.17,
  },
  {
    index: 266,
    cluster: 0,
    KAB_KOTA: "OGAN KOMERING ULU",
    ipm: 69.6,
  },
  {
    index: 267,
    cluster: 3,
    KAB_KOTA: "PACITAN",
    ipm: 68.57,
  },
  {
    index: 268,
    cluster: 3,
    KAB_KOTA: "PADANG LAWAS",
    ipm: 68.64,
  },
  {
    index: 269,
    cluster: 1,
    KAB_KOTA: "PADANG LAWAS UTARA",
    ipm: 70.11,
  },
  {
    index: 270,
    cluster: 3,
    KAB_KOTA: "PADANG PARIAMAN",
    ipm: 70.76,
  },
  {
    index: 271,
    cluster: 3,
    KAB_KOTA: "PAKPAK BHARAT",
    ipm: 67.94,
  },
  {
    index: 272,
    cluster: 0,
    KAB_KOTA: "PAMEKASAN",
    ipm: 66.4,
  },
  {
    index: 273,
    cluster: 3,
    KAB_KOTA: "PANDEGLANG",
    ipm: 65.17,
  },
  {
    index: 274,
    cluster: 0,
    KAB_KOTA: "PANGANDARAN",
    ipm: 68.28,
  },
  {
    index: 275,
    cluster: 3,
    KAB_KOTA: "PANGKAJENE DAN KEPULAUAN",
    ipm: 69.21,
  },
  {
    index: 276,
    cluster: 1,
    KAB_KOTA: "PANIAI",
    ipm: 56.7,
  },
  {
    index: 277,
    cluster: 3,
    KAB_KOTA: "PARIGI MOUTONG",
    ipm: 65.82,
  },
  {
    index: 278,
    cluster: 3,
    KAB_KOTA: "PASAMAN",
    ipm: 66.77,
  },
  {
    index: 279,
    cluster: 3,
    KAB_KOTA: "PASAMAN BARAT",
    ipm: 68.76,
  },
  {
    index: 280,
    cluster: 2,
    KAB_KOTA: "PASER",
    ipm: 72.93,
  },
  {
    index: 281,
    cluster: 0,
    KAB_KOTA: "PASURUAN",
    ipm: 68.93,
  },
  {
    index: 282,
    cluster: 3,
    KAB_KOTA: "PATI",
    ipm: 72.28,
  },
  {
    index: 283,
    cluster: 1,
    KAB_KOTA: "PEGUNUNGAN ARFAK",
    ipm: 56.13,
  },
  {
    index: 284,
    cluster: 1,
    KAB_KOTA: "PEGUNUNGAN BINTANG",
    ipm: 46.28,
  },
  {
    index: 285,
    cluster: 0,
    KAB_KOTA: "PEKALONGAN",
    ipm: 70.11,
  },
  {
    index: 286,
    cluster: 0,
    KAB_KOTA: "PELALAWAN",
    ipm: 72.08,
  },
  {
    index: 287,
    cluster: 3,
    KAB_KOTA: "PEMALANG",
    ipm: 66.56,
  },
  {
    index: 288,
    cluster: 3,
    KAB_KOTA: "PENAJAM PASER UTARA",
    ipm: 72.01,
  },
  {
    index: 289,
    cluster: 1,
    KAB_KOTA: "PENUKAL ABAB LEMATANG ILIR",
    ipm: 64.88,
  },
  {
    index: 290,
    cluster: 1,
    KAB_KOTA: "PESAWARAN",
    ipm: 66.14,
  },
  {
    index: 291,
    cluster: 1,
    KAB_KOTA: "PESISIR BARAT",
    ipm: 64.3,
  },
  {
    index: 292,
    cluster: 3,
    KAB_KOTA: "PESISIR SELATAN",
    ipm: 70.03,
  },
  {
    index: 293,
    cluster: 3,
    KAB_KOTA: "PIDIE",
    ipm: 70.7,
  },
  {
    index: 294,
    cluster: 1,
    KAB_KOTA: "PIDIE JAYA",
    ipm: 73.6,
  },
  {
    index: 295,
    cluster: 3,
    KAB_KOTA: "PINRANG",
    ipm: 71.45,
  },
  {
    index: 296,
    cluster: 3,
    KAB_KOTA: "POLEWALI MANDAR",
    ipm: 64.23,
  },
  {
    index: 297,
    cluster: 3,
    KAB_KOTA: "PONOROGO",
    ipm: 71.06,
  },
  {
    index: 298,
    cluster: 3,
    KAB_KOTA: "POSO",
    ipm: 71.45,
  },
  {
    index: 299,
    cluster: 3,
    KAB_KOTA: "PRINGSEWU",
    ipm: 70.45,
  },
  {
    index: 300,
    cluster: 3,
    KAB_KOTA: "PROBOLINGGO",
    ipm: 66.26,
  },
  {
    index: 301,
    cluster: 3,
    KAB_KOTA: "PULANG PISAU",
    ipm: 68.53,
  },
  {
    index: 302,
    cluster: 1,
    KAB_KOTA: "PULAU MOROTAI",
    ipm: 62.9,
  },
  {
    index: 303,
    cluster: 1,
    KAB_KOTA: "PULAU TALIABU",
    ipm: 60.73,
  },
  {
    index: 304,
    cluster: 1,
    KAB_KOTA: "PUNCAK",
    ipm: 43.17,
  },
  {
    index: 305,
    cluster: 1,
    KAB_KOTA: "PUNCAK JAYA",
    ipm: 48.99,
  },
  {
    index: 306,
    cluster: 3,
    KAB_KOTA: "PURBALINGGA",
    ipm: 69.15,
  },
  {
    index: 307,
    cluster: 0,
    KAB_KOTA: "PURWAKARTA",
    ipm: 70.98,
  },
  {
    index: 308,
    cluster: 3,
    KAB_KOTA: "PURWOREJO",
    ipm: 72.98,
  },
  {
    index: 309,
    cluster: 1,
    KAB_KOTA: "RAJA AMPAT",
    ipm: 63.92,
  },
  {
    index: 310,
    cluster: 3,
    KAB_KOTA: "REJANG LEBONG",
    ipm: 70.77,
  },
  {
    index: 311,
    cluster: 0,
    KAB_KOTA: "REMBANG",
    ipm: 70.43,
  },
  {
    index: 312,
    cluster: 0,
    KAB_KOTA: "ROKAN HILIR",
    ipm: 69.34,
  },
  {
    index: 313,
    cluster: 3,
    KAB_KOTA: "ROKAN HULU",
    ipm: 69.67,
  },
  {
    index: 314,
    cluster: 3,
    KAB_KOTA: "ROTE NDAO",
    ipm: 62.6,
  },
  {
    index: 315,
    cluster: 1,
    KAB_KOTA: "SABU RAIJUA",
    ipm: 57.03,
  },
  {
    index: 316,
    cluster: 1,
    KAB_KOTA: "SAMBAS",
    ipm: 67.1,
  },
  {
    index: 317,
    cluster: 3,
    KAB_KOTA: "SAMOSIR",
    ipm: 70.83,
  },
  {
    index: 318,
    cluster: 3,
    KAB_KOTA: "SAMPANG",
    ipm: 62.8,
  },
  {
    index: 319,
    cluster: 3,
    KAB_KOTA: "SANGGAU",
    ipm: 66.2,
  },
  {
    index: 320,
    cluster: 3,
    KAB_KOTA: "KEPULAUAN SANGIHE",
    ipm: 71.07,
  },
  {
    index: 321,
    cluster: 1,
    KAB_KOTA: "SARMI",
    ipm: 63.94,
  },
  {
    index: 322,
    cluster: 3,
    KAB_KOTA: "SAROLANGUN",
    ipm: 70.25,
  },
  {
    index: 323,
    cluster: 3,
    KAB_KOTA: "SEKADAU",
    ipm: 64.93,
  },
  {
    index: 324,
    cluster: 3,
    KAB_KOTA: "SELUMA",
    ipm: 67.03,
  },
  {
    index: 325,
    cluster: 0,
    KAB_KOTA: "SEMARANG",
    ipm: 74.24,
  },
  {
    index: 326,
    cluster: 3,
    KAB_KOTA: "SERAM BAGIAN BARAT",
    ipm: 65.83,
  },
  {
    index: 327,
    cluster: 1,
    KAB_KOTA: "SERAM BAGIAN TIMUR",
    ipm: 64.3,
  },
  {
    index: 328,
    cluster: 0,
    KAB_KOTA: "SERANG",
    ipm: 66.82,
  },
  {
    index: 329,
    cluster: 3,
    KAB_KOTA: "SERDANG BEDAGAI",
    ipm: 70.56,
  },
  {
    index: 330,
    cluster: 3,
    KAB_KOTA: "SERUYAN",
    ipm: 67.67,
  },
  {
    index: 331,
    cluster: 0,
    KAB_KOTA: "SIAK",
    ipm: 73.98,
  },
  {
    index: 332,
    cluster: 3,
    KAB_KOTA: "SIDENRENG RAPPANG",
    ipm: 71.54,
  },
  {
    index: 333,
    cluster: 2,
    KAB_KOTA: "SIDOARJO",
    ipm: 80.65,
  },
  {
    index: 334,
    cluster: 3,
    KAB_KOTA: "SIGI",
    ipm: 68.49,
  },
  {
    index: 335,
    cluster: 3,
    KAB_KOTA: "SIJUNJUNG",
    ipm: 67.86,
  },
  {
    index: 336,
    cluster: 1,
    KAB_KOTA: "SIKKA",
    ipm: 65.41,
  },
  {
    index: 337,
    cluster: 3,
    KAB_KOTA: "SIMALUNGUN",
    ipm: 73.4,
  },
  {
    index: 338,
    cluster: 3,
    KAB_KOTA: "SIMEULUE",
    ipm: 66.41,
  },
  {
    index: 339,
    cluster: 3,
    KAB_KOTA: "SINJAI",
    ipm: 67.75,
  },
  {
    index: 340,
    cluster: 3,
    KAB_KOTA: "SINTANG",
    ipm: 66.93,
  },
  {
    index: 341,
    cluster: 0,
    KAB_KOTA: "SITUBONDO",
    ipm: 67.78,
  },
  {
    index: 342,
    cluster: 2,
    KAB_KOTA: "SLEMAN",
    ipm: 84,
  },
  {
    index: 343,
    cluster: 3,
    KAB_KOTA: "SOLOK",
    ipm: 69.24,
  },
  {
    index: 344,
    cluster: 3,
    KAB_KOTA: "SOLOK SELATAN",
    ipm: 69.23,
  },
  {
    index: 345,
    cluster: 3,
    KAB_KOTA: "SOPPENG",
    ipm: 68.99,
  },
  {
    index: 346,
    cluster: 1,
    KAB_KOTA: "SORONG",
    ipm: 65.77,
  },
  {
    index: 347,
    cluster: 1,
    KAB_KOTA: "SORONG SELATAN",
    ipm: 62.46,
  },
  {
    index: 348,
    cluster: 0,
    KAB_KOTA: "SRAGEN",
    ipm: 74.08,
  },
  {
    index: 349,
    cluster: 0,
    KAB_KOTA: "SUBANG",
    ipm: 69.13,
  },
  {
    index: 350,
    cluster: 3,
    KAB_KOTA: "SUKABUMI",
    ipm: 67.07,
  },
  {
    index: 351,
    cluster: 3,
    KAB_KOTA: "SUKAMARA",
    ipm: 68.27,
  },
  {
    index: 352,
    cluster: 0,
    KAB_KOTA: "SUKOHARJO",
    ipm: 77.13,
  },
  {
    index: 353,
    cluster: 1,
    KAB_KOTA: "SUMBA BARAT",
    ipm: 63.83,
  },
  {
    index: 354,
    cluster: 1,
    KAB_KOTA: "SUMBA BARAT DAYA",
    ipm: 62.29,
  },
  {
    index: 355,
    cluster: 1,
    KAB_KOTA: "SUMBA TENGAH",
    ipm: 61.8,
  },
  {
    index: 356,
    cluster: 1,
    KAB_KOTA: "SUMBA TIMUR",
    ipm: 65.74,
  },
  {
    index: 357,
    cluster: 3,
    KAB_KOTA: "SUMBAWA",
    ipm: 68.01,
  },
  {
    index: 358,
    cluster: 3,
    KAB_KOTA: "SUMBAWA BARAT",
    ipm: 71.85,
  },
  {
    index: 359,
    cluster: 3,
    KAB_KOTA: "SUMEDANG",
    ipm: 71.8,
  },
  {
    index: 360,
    cluster: 3,
    KAB_KOTA: "SUMENEP",
    ipm: 67.04,
  },
  {
    index: 361,
    cluster: 1,
    KAB_KOTA: "SUPIORI",
    ipm: 62.72,
  },
  {
    index: 362,
    cluster: 0,
    KAB_KOTA: "TABALONG",
    ipm: 72.6,
  },
  {
    index: 363,
    cluster: 0,
    KAB_KOTA: "TABANAN",
    ipm: 76.45,
  },
  {
    index: 364,
    cluster: 0,
    KAB_KOTA: "TAKALAR",
    ipm: 67.72,
  },
  {
    index: 365,
    cluster: 1,
    KAB_KOTA: "TAMBRAUW",
    ipm: 53.71,
  },
  {
    index: 366,
    cluster: 3,
    KAB_KOTA: "TANA TIDUNG",
    ipm: 67.76,
  },
  {
    index: 367,
    cluster: 3,
    KAB_KOTA: "TANA TORAJA",
    ipm: 69.49,
  },
  {
    index: 368,
    cluster: 1,
    KAB_KOTA: "TANAH BUMBU",
    ipm: 71,
  },
  {
    index: 369,
    cluster: 3,
    KAB_KOTA: "TANAH DATAR",
    ipm: 72.46,
  },
  {
    index: 370,
    cluster: 0,
    KAB_KOTA: "TANAH LAUT",
    ipm: 69.87,
  },
  {
    index: 371,
    cluster: 2,
    KAB_KOTA: "TANGERANG",
    ipm: 72.29,
  },
  {
    index: 372,
    cluster: 3,
    KAB_KOTA: "TANGGAMUS",
    ipm: 66.65,
  },
  {
    index: 373,
    cluster: 3,
    KAB_KOTA: "TANJUNG JABUNG BARAT",
    ipm: 68.16,
  },
  {
    index: 374,
    cluster: 3,
    KAB_KOTA: "TANJUNG JABUNG TIMUR",
    ipm: 64.91,
  },
  {
    index: 375,
    cluster: 1,
    KAB_KOTA: "TAPANULI SELATAN",
    ipm: 70.33,
  },
  {
    index: 376,
    cluster: 3,
    KAB_KOTA: "TAPANULI TENGAH",
    ipm: 69.61,
  },
  {
    index: 377,
    cluster: 3,
    KAB_KOTA: "TAPANULI UTARA",
    ipm: 73.76,
  },
  {
    index: 378,
    cluster: 2,
    KAB_KOTA: "TAPIN",
    ipm: 70.31,
  },
  {
    index: 379,
    cluster: 3,
    KAB_KOTA: "TASIKMALAYA",
    ipm: 65.9,
  },
  {
    index: 380,
    cluster: 3,
    KAB_KOTA: "TEBO",
    ipm: 69.35,
  },
  {
    index: 381,
    cluster: 0,
    KAB_KOTA: "TEGAL",
    ipm: 68.79,
  },
  {
    index: 382,
    cluster: 1,
    KAB_KOTA: "TELUK BINTUNI",
    ipm: 64.65,
  },
  {
    index: 383,
    cluster: 1,
    KAB_KOTA: "TELUK WONDAMA",
    ipm: 60.33,
  },
  {
    index: 384,
    cluster: 3,
    KAB_KOTA: "TEMANGGUNG",
    ipm: 69.88,
  },
  {
    index: 385,
    cluster: 3,
    KAB_KOTA: "TIMOR TENGAH SELATAN",
    ipm: 62.16,
  },
  {
    index: 386,
    cluster: 1,
    KAB_KOTA: "TIMOR TENGAH UTARA",
    ipm: 63.69,
  },
  {
    index: 387,
    cluster: 3,
    KAB_KOTA: "TOBA SAMOSIR",
    ipm: 75.39,
  },
  {
    index: 388,
    cluster: 3,
    KAB_KOTA: "TOJO UNA-UNA",
    ipm: 64.74,
  },
  {
    index: 389,
    cluster: 1,
    KAB_KOTA: "TOLIKARA",
    ipm: 49.6,
  },
  {
    index: 390,
    cluster: 3,
    KAB_KOTA: "TORAJA UTARA",
    ipm: 69.75,
  },
  {
    index: 391,
    cluster: 0,
    KAB_KOTA: "TRENGGALEK",
    ipm: 70.06,
  },
  {
    index: 392,
    cluster: 0,
    KAB_KOTA: "TUBAN",
    ipm: 68.91,
  },
  {
    index: 393,
    cluster: 3,
    KAB_KOTA: "TULANG BAWANG BARAT",
    ipm: 66.22,
  },
  {
    index: 394,
    cluster: 0,
    KAB_KOTA: "TULUNGAGUNG",
    ipm: 73.15,
  },
  {
    index: 395,
    cluster: 3,
    KAB_KOTA: "WAJO",
    ipm: 69.62,
  },
  {
    index: 396,
    cluster: 3,
    KAB_KOTA: "WAKATOBI",
    ipm: 69.87,
  },
  {
    index: 397,
    cluster: 3,
    KAB_KOTA: "WAY KANAN",
    ipm: 67.57,
  },
  {
    index: 398,
    cluster: 3,
    KAB_KOTA: "WONOGIRI",
    ipm: 70.49,
  },
  {
    index: 399,
    cluster: 3,
    KAB_KOTA: "WONOSOBO",
    ipm: 68.43,
  },
  {
    index: 400,
    cluster: 1,
    KAB_KOTA: "YAHUKIMO",
    ipm: 49.48,
  },
  {
    index: 401,
    cluster: 1,
    KAB_KOTA: "YALIMO",
    ipm: 49.01,
  },
  {
    index: 402,
    cluster: 0,
    KAB_KOTA: "KOTA AMBON",
    ipm: 81.23,
  },
  {
    index: 403,
    cluster: 2,
    KAB_KOTA: "KOTA BALIKPAPAN",
    ipm: 80.71,
  },
  {
    index: 404,
    cluster: 0,
    KAB_KOTA: "KOTA BANDA ACEH",
    ipm: 85.71,
  },
  {
    index: 405,
    cluster: 2,
    KAB_KOTA: "KOTA BANDAR LAMPUNG",
    ipm: 77.58,
  },
  {
    index: 406,
    cluster: 2,
    KAB_KOTA: "KOTA BANDUNG",
    ipm: 81.96,
  },
  {
    index: 407,
    cluster: 0,
    KAB_KOTA: "KOTA BANJAR",
    ipm: 71.92,
  },
  {
    index: 408,
    cluster: 2,
    KAB_KOTA: "KOTA BANJARMASIN",
    ipm: 77.57,
  },
  {
    index: 409,
    cluster: 2,
    KAB_KOTA: "KOTA BATAM",
    ipm: 81.12,
  },
  {
    index: 410,
    cluster: 0,
    KAB_KOTA: "KOTA BATU",
    ipm: 76.28,
  },
  {
    index: 411,
    cluster: 2,
    KAB_KOTA: "KOTA BEKASI",
    ipm: 81.95,
  },
  {
    index: 412,
    cluster: 0,
    KAB_KOTA: "KOTA BENGKULU",
    ipm: 80.54,
  },
  {
    index: 413,
    cluster: 3,
    KAB_KOTA: "KOTA BIMA",
    ipm: 76.11,
  },
  {
    index: 414,
    cluster: 0,
    KAB_KOTA: "KOTA BINJAI",
    ipm: 76.01,
  },
  {
    index: 415,
    cluster: 3,
    KAB_KOTA: "KOTA BITUNG",
    ipm: 74.2,
  },
  {
    index: 416,
    cluster: 2,
    KAB_KOTA: "KOTA BLITAR",
    ipm: 78.98,
  },
  {
    index: 417,
    cluster: 2,
    KAB_KOTA: "KOTA BOGOR",
    ipm: 76.59,
  },
  {
    index: 418,
    cluster: 0,
    KAB_KOTA: "KOTA BONTANG",
    ipm: 80.59,
  },
  {
    index: 419,
    cluster: 0,
    KAB_KOTA: "KOTA BUKITTINGGI",
    ipm: 80.7,
  },
  {
    index: 420,
    cluster: 2,
    KAB_KOTA: "KOTA CILEGON",
    ipm: 73.35,
  },
  {
    index: 421,
    cluster: 2,
    KAB_KOTA: "KOTA CIMAHI",
    ipm: 78.06,
  },
  {
    index: 422,
    cluster: 2,
    KAB_KOTA: "KOTA CIREBON",
    ipm: 75.25,
  },
  {
    index: 423,
    cluster: 2,
    KAB_KOTA: "KOTA DENPASAR",
    ipm: 84.03,
  },
  {
    index: 424,
    cluster: 2,
    KAB_KOTA: "KOTA DEPOK",
    ipm: 81.37,
  },
  {
    index: 425,
    cluster: 2,
    KAB_KOTA: "KOTA DUMAI",
    ipm: 74.75,
  },
  {
    index: 426,
    cluster: 2,
    KAB_KOTA: "KOTA GORONTALO",
    ipm: 77.41,
  },
  {
    index: 427,
    cluster: 3,
    KAB_KOTA: "KOTA GUNUNGSITOLI",
    ipm: 69.61,
  },
  {
    index: 428,
    cluster: 2,
    KAB_KOTA: "KOTA JAMBI",
    ipm: 79.12,
  },
  {
    index: 429,
    cluster: 0,
    KAB_KOTA: "KOTA JAYAPURA",
    ipm: 80.11,
  },
  {
    index: 430,
    cluster: 2,
    KAB_KOTA: "KOTA KEDIRI",
    ipm: 78.6,
  },
  {
    index: 431,
    cluster: 2,
    KAB_KOTA: "KOTA KENDARI",
    ipm: 84.15,
  },
  {
    index: 432,
    cluster: 3,
    KAB_KOTA: "KOTA KOTAMOBAGU",
    ipm: 73.47,
  },
  {
    index: 433,
    cluster: 0,
    KAB_KOTA: "KOTA KUPANG",
    ipm: 79.74,
  },
  {
    index: 434,
    cluster: 0,
    KAB_KOTA: "KOTA LANGSA",
    ipm: 77.44,
  },
  {
    index: 435,
    cluster: 3,
    KAB_KOTA: "KOTA LHOKSEUMAWE",
    ipm: 77.57,
  },
  {
    index: 436,
    cluster: 0,
    KAB_KOTA: "KOTA LUBUKLINGGAU",
    ipm: 74.89,
  },
  {
    index: 437,
    cluster: 0,
    KAB_KOTA: "KOTA MADIUN",
    ipm: 81.25,
  },
  {
    index: 438,
    cluster: 0,
    KAB_KOTA: "KOTA MAGELANG",
    ipm: 79.43,
  },
  {
    index: 439,
    cluster: 2,
    KAB_KOTA: "KOTA MALANG",
    ipm: 82.04,
  },
  {
    index: 440,
    cluster: 2,
    KAB_KOTA: "KOTA MANADO",
    ipm: 79.2,
  },
  {
    index: 441,
    cluster: 0,
    KAB_KOTA: "KOTA MATARAM",
    ipm: 79.14,
  },
  {
    index: 442,
    cluster: 2,
    KAB_KOTA: "KOTA MEDAN",
    ipm: 81.21,
  },
  {
    index: 443,
    cluster: 0,
    KAB_KOTA: "KOTA METRO",
    ipm: 77.49,
  },
  {
    index: 444,
    cluster: 2,
    KAB_KOTA: "KOTA MOJOKERTO",
    ipm: 78.43,
  },
  {
    index: 445,
    cluster: 2,
    KAB_KOTA: "KOTA PADANG",
    ipm: 82.9,
  },
  {
    index: 446,
    cluster: 0,
    KAB_KOTA: "KOTA PADANG PANJANG",
    ipm: 77.97,
  },
  {
    index: 447,
    cluster: 3,
    KAB_KOTA: "KOTA PAGAR ALAM",
    ipm: 68.68,
  },
  {
    index: 448,
    cluster: 2,
    KAB_KOTA: "KOTA PALEMBANG",
    ipm: 78.72,
  },
  {
    index: 449,
    cluster: 0,
    KAB_KOTA: "KOTA PALOPO",
    ipm: 78.38,
  },
  {
    index: 450,
    cluster: 0,
    KAB_KOTA: "KOTA PALU",
    ipm: 81.7,
  },
  {
    index: 451,
    cluster: 3,
    KAB_KOTA: "KOTA PARIAMAN",
    ipm: 77.07,
  },
  {
    index: 452,
    cluster: 0,
    KAB_KOTA: "KOTA PASURUAN",
    ipm: 75.62,
  },
  {
    index: 453,
    cluster: 0,
    KAB_KOTA: "KOTA PAYAKUMBUH",
    ipm: 79.08,
  },
  {
    index: 454,
    cluster: 0,
    KAB_KOTA: "KOTA PEKALONGAN",
    ipm: 75.4,
  },
  {
    index: 455,
    cluster: 2,
    KAB_KOTA: "KOTA PEKANBARU",
    ipm: 81.58,
  },
  {
    index: 456,
    cluster: 2,
    KAB_KOTA: "KOTA PONTIANAK",
    ipm: 79.93,
  },
  {
    index: 457,
    cluster: 0,
    KAB_KOTA: "KOTA PRABUMULIH",
    ipm: 74.67,
  },
  {
    index: 458,
    cluster: 2,
    KAB_KOTA: "KOTA PROBOLINGGO",
    ipm: 73.66,
  },
  {
    index: 459,
    cluster: 0,
    KAB_KOTA: "KOTA SABANG",
    ipm: 76.11,
  },
  {
    index: 460,
    cluster: 0,
    KAB_KOTA: "KOTA SALATIGA",
    ipm: 83.6,
  },
  {
    index: 461,
    cluster: 2,
    KAB_KOTA: "KOTA SAMARINDA",
    ipm: 80.76,
  },
  {
    index: 462,
    cluster: 2,
    KAB_KOTA: "KOTA SEMARANG",
    ipm: 83.55,
  },
  {
    index: 463,
    cluster: 0,
    KAB_KOTA: "KOTA SERANG",
    ipm: 72.44,
  },
  {
    index: 464,
    cluster: 0,
    KAB_KOTA: "KOTA SIBOLGA",
    ipm: 73.94,
  },
  {
    index: 465,
    cluster: 0,
    KAB_KOTA: "KOTA SINGKAWANG",
    ipm: 72.11,
  },
  {
    index: 466,
    cluster: 0,
    KAB_KOTA: "KOTA SOLOK",
    ipm: 78.41,
  },
  {
    index: 467,
    cluster: 0,
    KAB_KOTA: "KOTA SORONG",
    ipm: 78.49,
  },
  {
    index: 468,
    cluster: 1,
    KAB_KOTA: "KOTA SUBULUSSALAM",
    ipm: 65.27,
  },
  {
    index: 469,
    cluster: 0,
    KAB_KOTA: "KOTA SUKABUMI",
    ipm: 74.6,
  },
  {
    index: 470,
    cluster: 3,
    KAB_KOTA: "KOTA SUNGAI PENUH",
    ipm: 75.7,
  },
  {
    index: 471,
    cluster: 2,
    KAB_KOTA: "KOTA SURABAYA",
    ipm: 82.31,
  },
  {
    index: 472,
    cluster: 2,
    KAB_KOTA: "KOTA SURAKARTA",
    ipm: 82.62,
  },
  {
    index: 473,
    cluster: 2,
    KAB_KOTA: "KOTA TANGERANG",
    ipm: 78.5,
  },
  {
    index: 474,
    cluster: 2,
    KAB_KOTA: "KOTA TANGERANG SELATAN",
    ipm: 81.6,
  },
  {
    index: 475,
    cluster: 3,
    KAB_KOTA: "KOTA TANJUNG BALAI",
    ipm: 68.94,
  },
  {
    index: 476,
    cluster: 0,
    KAB_KOTA: "KOTA TARAKAN",
    ipm: 76.23,
  },
  {
    index: 477,
    cluster: 0,
    KAB_KOTA: "KOTA TASIKMALAYA",
    ipm: 73.31,
  },
  {
    index: 478,
    cluster: 0,
    KAB_KOTA: "KOTA TEBING TINGGI",
    ipm: 75.42,
  },
  {
    index: 479,
    cluster: 2,
    KAB_KOTA: "KOTA TEGAL",
    ipm: 75.52,
  },
  {
    index: 480,
    cluster: 3,
    KAB_KOTA: "KOTA TERNATE",
    ipm: 80.14,
  },
  {
    index: 481,
    cluster: 3,
    KAB_KOTA: "KOTA TIDORE KEPULAUAN",
    ipm: 70.99,
  },
  {
    index: 482,
    cluster: 0,
    KAB_KOTA: "KOTA TOMOHON",
    ipm: 76.86,
  },
  {
    index: 483,
    cluster: 1,
    KAB_KOTA: "KOTA TUAL",
    ipm: 68.16,
  },
  {
    index: 484,
    cluster: 2,
    KAB_KOTA: "KOTA YOGYAKARTA",
    ipm: 87.18,
  },
];
